CREATE TABLE PROVEEDOR(
ID_PROVEEDOR NUMBER(10) CONSTRAINT PK_PERSONA  PRIMARY KEY,
IDENTIFICACION NUMBER(20),
NOMBRE VARCHAR2(25),
EMAIL VARCHAR2(25),
DIRECCION VARCHAR2(50),
CONTACTO VARCHAR2(50),
ID_TIPO_PROV NUMBER(10), 
FECHA_INGRESO DATE,
ESTADO VARCHAR2(10)--ACTIVO O NO
);
 ALTER TABLE PROVEEDOR ADD CONSTRAINT UK_IDENTIFICACION UNIQUE(IDENTIFICACION);
ALTER TABLE PROVEEDOR ADD CONSTRAINT CK_ESTADO CHECK (ESTADO IN ('ACTIVO','NO ACTIVO'));


CREATE TABLE TIPO_PROVEEDOR(
ID_TIPO_PRO NUMBER(10) CONSTRAINT PK_ID_TIPO_PRO  PRIMARY KEY,
TIPO_PRO VARCHAR2(20)
);


CREATE TABLE CLIENTE (
ID_CLIENTE NUMBER(10) CONSTRAINT PK_ID_CLIENTE PRIMARY KEY,
IDENTIFICACION NUMBER(20),
NOMBRE_ VARCHAR2(25),
APELLIDO1 VARCHAR2(50),
APELLIDO2  VARCHAR2(50),
SEXO CHAR,
FECHA_NACIMIENTO DATE,
FECHA_INGRESO DATE,
ESTATUS VARCHAR2(30),
CATEGORIA VARCHAR2(10),
LIMITE_CREDITO NUMBER(10),
ID_DIRECCION NUMBER(10) 
);
ALTER TABLE CLIENTE ADD CONSTRAINT CK_SEXO CHECK (SEXO IN ('M','F'));
 ALTER TABLE CLIENTE ADD CONSTRAINT UK_CLIEN_IDENTIFICACION UNIQUE(IDENTIFICACION);

CREATE TABLE CONTACTO(
ID_CONTACTO NUMBER(10)CONSTRAINT PK_ID_CONTACTO  PRIMARY KEY,
IDCLIENTE NUMBER(10),
TIPO VARCHAR2(10),
VALOR NUMBER(20),
ESTADO VARCHAR2(20)
);


CREATE TABLE EMPLEADO (
ID_EMPLEADO NUMBER(10) CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY,
NOMBRE VARCHAR2(25),
NOMBRE2 VARCHAR2(25),
APELLIDO1 VARCHAR2(50),
APELLIDO2  VARCHAR2(50),
EMAIL VARCHAR2(25),
ID_JEFE NUMBER(25),
ID_DEPTO NUMBER(20),
ID_PUESTO NUMBER(20),
SEXO CHAR
);
ALTER TABLE EMPLEADO ADD CONSTRAINT CK_EMPLEADO_SEXO CHECK (SEXO IN ('M','F'));

CREATE TABLE PUESTO(
ID_PUESTO NUMBER(20) CONSTRAINT PK_ID_PUESTO  PRIMARY KEY,
NOMBRE_PUESTO VARCHAR2(30),
SALARIO NUMBER(20),
COSTO_HORA NUMBER(20),
JORNADA VARCHAR2(30),
FECHA_CREACION DATE,
TIPO VARCHAR2(20)
);

CREATE TABLE PRODUCTOS (
ID_PRODUCTO NUMBER(10) CONSTRAINT PK_PRODUCTO PRIMARY KEY,
NOMBRE_PRODUCTO VARCHAR2(25),
PRECIO_UNITARIO NUMBER(25),
ID_PROVEEDOR NUMBER(25),
MARCA VARCHAR2(30),
PRESENTACION VARCHAR2(50)
);

CREATE TABLE INVENTARIO(
ID_INVENTARIO NUMBER(30)CONSTRAINT PK_INVENTARIO PRIMARY KEY,
ID_PRODUCTO NUMBER(30),
CANTIDAD_EXISTENCIA NUMBER(20),
MONTO_TOTAL NUMBER(25)
);

CREATE TABLE FACTURA(
ID_FACTURA NUMBER(10)CONSTRAINT PK_ID_FACTURA PRIMARY KEY,
ID_CLIENTE NUMBER(25),
FECHA DATE,
ID_DETALLE_F NUMBER(30),
ID_EMPLEADO NUMBER(30),
MONTO_TOTAL NUMBER(30)
);

CREATE TABLE DETALLE_FACTURA(
ID_DETALLE_F NUMBER(30)CONSTRAINT PK_ID_DETALLE_F PRIMARY KEY,
ID_PRODUCTO NUMBER(30),
CANTIDAD NUMBER(25),
PRECIO_VENTA NUMBER(25)
);

CREATE TABLE PEDIDO(
ID_PEDIDO NUMBER(10) CONSTRAINT PK_ID_PEDIDO PRIMARY KEY,
ID_PROVEEDOR NUMBER(10),
ID_DETALLE_PEDIDO NUMBER(30),
FECHA DATE,
USUARIO VARCHAR2(30),
ESTADO VARCHAR2(15)--entregado/pendiente/anulado
);

ALTER TABLE PEDIDO ADD CONSTRAINT CK_ESTADO_PEDIDO CHECK (ESTADO IN ('ENTREGADO','PENDIENTE','ANULADO'));

CREATE TABLE DETALLE_PEDIDO(
ID_DETALLE_P NUMBER(30)CONSTRAINT PK_ID_DETALLE_P PRIMARY KEY,
ID_PRODUCTO NUMBER(30),
CANTIDAD NUMBER(30),
PRECIO_COMPRA NUMBER(25),
PRECIO_VENTA NUMBER(25)
);



CREATE TABLE TIPO_PAGO(
ID_PAGO NUMBER(10) CONSTRAINT PK_ID_PAGO PRIMARY KEY,
TIPO_PAGO VARCHAR2(20)
);

CREATE TABLE DIRECCION(
ID_DIRECCION NUMBER(10) CONSTRAINT PK_ID_DIRECCION PRIMARY KEY,
ID_CLIENTE NUMBER(25),
PROVINCIA NUMBER(25),
CANTON NUMBER(25),
DISTRITO NUMBER(25),
OTRAS_SENAS VARCHAR2(25)
);

CREATE TABLE DEPARTAMENTO(
ID_DEPTO NUMBER(20) CONSTRAINT PK_ID_DEPTO PRIMARY KEY,
NOMBRE VARCHAR2(30),
ID_DIRECCION NUMBER(30)
);
